const appRoutesWithParameters = {
  root: "/",
  verifyEmail: "/verifyemail",
  login: "/login",
  register: "/register",
  forgotPassword: "/forgotpassword",
  resetPassword: "/resetpassword",
  project: "/project",
  dashboard: "/dashboard",
  component: "/component",
  subComponent: "/sub-component",
  document: "/document",
  activity: "/activity",
  subActivity: "/sub-activity",
  process: "/process",
  dashboardDocument: "/dashboard/documentDetail",
  userManagement: "/user-management",
  codeList: "/code-list",
};

export const appRoute = {
  root: `${appRoutesWithParameters.root}`,
  verifyEmail: `${appRoutesWithParameters.verifyEmail}`,
  login: `${appRoutesWithParameters.login}`,
  register: `${appRoutesWithParameters.register}`,
  forgotPassword: `${appRoutesWithParameters.forgotPassword}`,
  resetPassword: `${appRoutesWithParameters.resetPassword}`,

  project: `${appRoutesWithParameters.project}`,
  dashboard: `${appRoutesWithParameters.dashboard}`,
  component: `${appRoutesWithParameters.component}`,
  subComponent: `${appRoutesWithParameters.subComponent}`,
  document: `${appRoutesWithParameters.document}`,
  activity: `${appRoutesWithParameters.activity}`,
  subActivity: `${appRoutesWithParameters.subActivity}`,
  process: `${appRoutesWithParameters.process}`,
  dashboardDocument: `${appRoutesWithParameters.dashboardDocument}`,
  userManagement: `${appRoutesWithParameters.userManagement}`,
  codeList: `${appRoutesWithParameters.codeList}`,
};
